services:
  db:
    image: mysql:8.0
    container_name: traseu_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: traseu2026
      MYSQL_DATABASE: traseu
      MYSQL_USER: traseu_user
      MYSQL_PASSWORD: traseu2026
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ptraseu2026",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: ./backend
    container_name: traseu_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: traseu_user
      DB_PASSWORD: traseu2026
      DB_NAME: traseu
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app/public

volumes:
  db_data:
