CREATE DATABASE IF NOT EXISTS traseu CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE traseu;

CREATE TABLE IF NOT EXISTS locations (
  id VARCHAR(32) PRIMARY KEY,
  data JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_state (
  key_name VARCHAR(64) PRIMARY KEY,
  value JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
